// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL1uZcqKiR4EKtjC154NPCIltjvlEquJs',
    appId: '1:645380850761:web:52cffa54fec8955cb82b98',
    messagingSenderId: '645380850761',
    projectId: 'educationalflutterapp-94f27',
    authDomain: 'educationalflutterapp-94f27.firebaseapp.com',
    storageBucket: 'educationalflutterapp-94f27.appspot.com',
    measurementId: 'G-MXHM4TLQSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARSpIAz2qv9rjcLXO1ar5zn5js81_wVp0',
    appId: '1:645380850761:android:6d43f2a4401a6c19b82b98',
    messagingSenderId: '645380850761',
    projectId: 'educationalflutterapp-94f27',
    storageBucket: 'educationalflutterapp-94f27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiM0Uc-2u5A4zXKWLiiySZWuIr6r4MBIg',
    appId: '1:645380850761:ios:7872faf040ccb018b82b98',
    messagingSenderId: '645380850761',
    projectId: 'educationalflutterapp-94f27',
    storageBucket: 'educationalflutterapp-94f27.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiM0Uc-2u5A4zXKWLiiySZWuIr6r4MBIg',
    appId: '1:645380850761:ios:c2ac4c70f3cfdca9b82b98',
    messagingSenderId: '645380850761',
    projectId: 'educationalflutterapp-94f27',
    storageBucket: 'educationalflutterapp-94f27.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
